version: '3.4'

services:
  goodreadstelegrambot:
    image: ${DOCKER_REGISTRY-}goodreadstelegrambot
    build:
      context: .
      dockerfile: GoodreadsTelegramBot/Dockerfile
    volumes:
      - /var/log:/app/log/bots